apiVersion: v1
kind: Pod
metadata:
  name: http-server
  namespace: http-server
spec:
  terminationGracePeriodSeconds: 30
  containers:
    - name: http-server
      image: bai615/go-httpserver:1.0.1

      # 优雅启动
      startupProbe:
        httpGet:
          host: 127.0.0.1
          scheme: HTTP
          path: /
          port: http-server-port
        failureThreshold: 30
        periodSeconds: 2

      # 探活
      livenessProbe:
        httpGet:
          host: 127.0.0.1
          scheme: HTTP
          path: /healthz
          port: http-server-port
        failureThreshold: 1
        periodSeconds: 10

      # 优雅终止
      lifecycle:
        preStop:
          exec:
            command: [ "/bin/sh", "-c", "kill -SIGTERM `pidof httpserver`" ]

      resources:
        # QoS保证：Guaranteed
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi

      # 配置和代码分离
      volumeMounts:
        - name: mhs-config
          mountPath: /conf
          readOnly: true
      args:
        - -c
        - /conf/config.json
      ports:
        - name: http-server-port
          containerPort: 8888
          hostPort: 80


  volumes:
    - name: http-server-config
      configMap:
        name: http-server-config
        defaultMode: 400

